In [ ]:
# Q1
import numpy as np
n = int(input("Enter no. of elements: "))
arr = np.empty(0, dtype='int')
for i in range(0, n):
  inp = int(input())
  arr = np.append(arr, inp)
print("Array: ", arr)
even = np.empty(0, dtype='int')
odd = np.empty(0, dtype='int')
for i in range(0, n):
  if ((arr[i]%2) == 0):
    even = np.append(even, arr[i])
  elif ((arr[i]%2) != 0):
    odd = np.append(odd, arr[i])
print("Even: ", even)
print("Odd: ", odd)
for i in range(0, n):
  if ((arr[i]%2) == 0):
    arr[i] = 0
print("Final array: ", arr)

Enter no. of elements: 5
3
6
9
12
15
Array:  [ 3  6  9 12 15]
Even:  [ 6 12]
Odd:  [ 3  9 15]
Final array:  [ 3  0  9  0 15]


In [ ]:
# Q2
import numpy as np
n = int(input("Enter no. of elements: "))
arr = np.empty(0, dtype='int')
for i in range(0, n):
  inp = int(input())
  arr = np.append(arr, inp)
print("Array: ", arr)
print("Array: ", (np.where((arr%2!=0), 'odd', arr)))

Enter no. of elements: 5
3
6
9
12
15
Array:  [ 3  6  9 12 15]
Array:  ['odd' '6' 'odd' '12' 'odd']


In [ ]:
# Q3
import numpy as np
arr = ['How', 'Are', 'You']
print("Array: ", arr)
ans = np.array(arr)
ans = np.repeat(ans, 3)
arr = arr*3
ans = np.append(ans, arr)
print(ans)

Array:  ['How', 'Are', 'You']
['How' 'How' 'How' 'Are' 'Are' 'Are' 'You' 'You' 'You' 'How' 'Are' 'You'
 'How' 'Are' 'You' 'How' 'Are' 'You']


In [ ]:
# Q4
import numpy as np
n = int(input("Enter no. of elements for array 1: "))
arr1 = np.empty(0)
for i in range(0, n):
  inp = input()
  arr1 = np.append(arr1, inp)
print("Array 1: ", arr1)
m = int(input("Enter no. of elements for array 2: "))
arr2 = np.empty(0)
for i in range(0, m):
  inp = input()
  arr2 = np.append(arr2, inp)
print("Array 2: ", arr2)
print("Common alphabets: ", np.intersect1d(arr1, arr2))

Enter no. of elements for array 1: 5
m
a
h
e
k
Array 1:  ['m' 'a' 'h' 'e' 'k']
Enter no. of elements for array 2: 7
k
h
o
w
a
l
a
Array 2:  ['k' 'h' 'o' 'w' 'a' 'l' 'a']
Common alphabets:  ['a' 'h' 'k']


In [ ]:
# Q5
import numpy as np
arr = np.arange(12).reshape(3, 4)
print("Original array: ")
print(arr)
arr[:,[0, 1]] = arr[:,[1, 0]]
print("Array after swapping columns: ")
print(arr)
arr[[0, 1], :] = arr[[1, 0], :]
print("Array after swapping rows: ")
print(arr)

Original array: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Array after swapping columns: 
[[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]]
Array after swapping rows: 
[[ 5  4  6  7]
 [ 1  0  2  3]
 [ 9  8 10 11]]


In [ ]:
# Q6
randomArray = np.random.uniform(6, 12, size=(5, 3))
print(randomArray)

[[ 7.90093867  7.14535497 11.27207044]
 [11.0348292  10.62077193  9.74292444]
 [ 8.48733284  9.84768323  6.11397174]
 [10.29185736  9.9508266   8.29494069]
 [ 7.84394441  7.49558015  7.17310339]]


In [ ]:
# Q7
import random
n = int(input("Enter no. of elements: "))
arr = np.empty(0)
for i in range(0, n):
    inp = round(random.uniform(3.00, 30.00), 2)
    arr = np.append(arr, inp)
print(arr)

Enter no. of elements: 6
[28.09 23.06  5.99 27.77 25.36  3.52]


In [ ]:
# Q8
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None, encoding=None)
print(iris_1d[:5])
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
print(iris_2d[:5])

[(5.1, 3.5, 1.4, 0.2, 'Iris-setosa') (4.9, 3. , 1.4, 0.2, 'Iris-setosa')
 (4.7, 3.2, 1.3, 0.2, 'Iris-setosa') (4.6, 3.1, 1.5, 0.2, 'Iris-setosa')
 (5. , 3.6, 1.4, 0.2, 'Iris-setosa')]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [ ]:
# Q9
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
mean = np.mean(sepallength)
median = np.median(sepallength)
standard_deviation = np.std(sepallength)
print("Mean: ", mean)
print("Median: ", median)
print("Standard deviation: ", standard_deviation)

Mean:  5.843333333333334
Median:  5.8
Standard deviation:  0.8253012917851409
